spring.application.name=mybackend

server.port=80

spring.web.resources.static-locations=classpath:/static/browser/

management.endpoints.web.exposure.include=httpexchanges

# pretty print json output wont work
#spring.jackson.serialization.indent-output=true